language: python
sudo: true
install:
  # The ultimate one-liner setup for NeuroDebian repository
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - pip install sphinx
  - sudo apt-get install git-annex-standalone
script: 
  - make -C docs html
